#include "RbqConstants_.idl"
#include "ImuInfo_.idl"
#include "JointInfo_.idl"
#include "TaskInfo_.idl"
#include "ContactInfo_.idl"

module rbq_msgs {
  module msg {
    module dds_ {

      @extensibility(APPENDABLE)
      struct SimInfo_ {
        ImuInfo_   imu;
        JointInfo_ leg_joint[MAX_LEG_JOINT];
        JointInfo_ arm_joint[MAX_ARM_JOINT];
        JointInfo_ whl_joint[MAX_WHL_JOINT];

        TaskInfo_    body_task;
        ContactInfo_ leg_contact[MAX_LEG_CONTACT];
      };

    };
  };
};

