#include "RbqConstants_.idl"
#include "JointInfo_.idl"

module rbq_msgs {
  module msg {
    module dds_ {

      @extensibility(APPENDABLE)
      struct WhlJointInfo_ {
        JointInfo_ joint[MAX_WHL_JOINT];
      };

    };
  };
};

