#include "ResponseHeader_.idl"

module api {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct Response_ {
        api::msg::dds_::ResponseHeader_ header;
        string data;
        sequence<octet> binary;
      };
    };
  };
};
