#include "Header_.idl"

module sensor_msgs {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct Joy_ {
        std_msgs::msg::dds_::Header_ header;
        sequence<float> axes;
        sequence<int32> buttons;
      };
    };
  };
};
