#include "Pose_.idl"
#include "Header_.idl"

module geometry_msgs {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct PoseStamped_ {
        std_msgs::msg::dds_::Header_ header;
        geometry_msgs::msg::dds_::Pose_ pose;
      };
    };
  };
};
