#include "Vector3_.idl"

module geometry_msgs {
  module msg {
    module dds_ {
      @extensibility(FINAL)
      struct Twist_ {
        geometry_msgs::msg::dds_::Vector3_ linear;
        geometry_msgs::msg::dds_::Vector3_ angular;
      };
    };
  };
};
